// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nl.Data;

namespace nl.Data.Migrations
{
    [DbContext(typeof(NlTutContext))]
    [Migration("20220113104939_ScreensizeFix")]
    partial class ScreensizeFix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("nl.Commen.Models.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("NextQuestionId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Answer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("54c2fc2f-4fe0-4523-92d1-19a5c1ac2351"),
                            NextQuestionId = 2,
                            OrderId = 1,
                            QuestionId = 1,
                            Text = "300-500"
                        },
                        new
                        {
                            Id = new Guid("06d3fb09-26cf-4eac-9274-e5ba139e36cd"),
                            NextQuestionId = 2,
                            OrderId = 2,
                            QuestionId = 1,
                            Text = "500-800"
                        },
                        new
                        {
                            Id = new Guid("08ce0ae4-b675-4734-9aea-93d93950bddd"),
                            NextQuestionId = 2,
                            OrderId = 3,
                            QuestionId = 1,
                            Text = "800-1200"
                        },
                        new
                        {
                            Id = new Guid("6c4dc7c1-f1f4-4ba8-b1ff-4eb5e5ec794d"),
                            NextQuestionId = 2,
                            OrderId = 4,
                            QuestionId = 1,
                            Text = "1200+"
                        },
                        new
                        {
                            Id = new Guid("04ee6a3e-c20c-4223-b992-931ae2eb5bd5"),
                            NextQuestionId = 7,
                            OrderId = 1,
                            QuestionId = 2,
                            Text = "Mail / Netflix & YouTube"
                        },
                        new
                        {
                            Id = new Guid("72649d68-0dfc-4f54-b3e4-9eaec38358ac"),
                            NextQuestionId = 7,
                            OrderId = 2,
                            QuestionId = 2,
                            Text = "Documenten bewerken"
                        },
                        new
                        {
                            Id = new Guid("8dcae819-c728-4870-8579-d3b7cb88bce0"),
                            NextQuestionId = 3,
                            OrderId = 3,
                            QuestionId = 2,
                            Text = "Foto's/video's bewerken"
                        },
                        new
                        {
                            Id = new Guid("935cd833-1040-4ebb-938d-fe0310f819a6"),
                            NextQuestionId = 4,
                            OrderId = 4,
                            QuestionId = 2,
                            Text = "Gamen"
                        },
                        new
                        {
                            Id = new Guid("b69989cb-7f86-497c-8303-6ab3ffb00f4b"),
                            NextQuestionId = 6,
                            OrderId = 1,
                            QuestionId = 3,
                            Text = "Foto's"
                        },
                        new
                        {
                            Id = new Guid("639a0d58-e3fe-4f5d-8082-801a8eb9625e"),
                            NextQuestionId = 6,
                            OrderId = 2,
                            QuestionId = 3,
                            Text = "Video's"
                        },
                        new
                        {
                            Id = new Guid("6f829325-e61f-4b0e-bf67-92040ead11a9"),
                            NextQuestionId = 5,
                            OrderId = 1,
                            QuestionId = 4,
                            Text = "Shooters"
                        },
                        new
                        {
                            Id = new Guid("a1c53f2f-9746-4246-a759-e8aa030ee0f4"),
                            NextQuestionId = 5,
                            OrderId = 2,
                            QuestionId = 4,
                            Text = "Moba"
                        },
                        new
                        {
                            Id = new Guid("73d9f4e4-0eb4-415d-8b57-66d3b5e4fe90"),
                            NextQuestionId = 5,
                            OrderId = 3,
                            QuestionId = 4,
                            Text = "Action-adventure"
                        },
                        new
                        {
                            Id = new Guid("2a6eb579-7610-4e1a-a8dd-b8a6dcfb6bea"),
                            NextQuestionId = 5,
                            OrderId = 4,
                            QuestionId = 4,
                            Text = "Esports"
                        },
                        new
                        {
                            Id = new Guid("17db2455-4c75-40ce-a5db-72825153c497"),
                            NextQuestionId = 5,
                            OrderId = 5,
                            QuestionId = 4,
                            Text = "Real-time strategy"
                        },
                        new
                        {
                            Id = new Guid("f17448be-f302-4b7a-b988-c7f2ddf665db"),
                            NextQuestionId = 8,
                            OrderId = 1,
                            QuestionId = 5,
                            Text = "Counter-Strike: Global Offensive"
                        },
                        new
                        {
                            Id = new Guid("fb23ced0-313f-4e9f-85c7-187ff80f8e52"),
                            NextQuestionId = 8,
                            OrderId = 2,
                            QuestionId = 5,
                            Text = "New World"
                        },
                        new
                        {
                            Id = new Guid("587d1938-ccd5-453d-b103-a394ce33306e"),
                            NextQuestionId = 8,
                            OrderId = 3,
                            QuestionId = 5,
                            Text = "Dota 2"
                        },
                        new
                        {
                            Id = new Guid("caa59a40-1b3f-41f1-9d9c-8af23d5987d2"),
                            NextQuestionId = 8,
                            OrderId = 4,
                            QuestionId = 5,
                            Text = "Battlefield 2042"
                        },
                        new
                        {
                            Id = new Guid("88d35685-076d-45c8-a549-af73be14a78d"),
                            NextQuestionId = 8,
                            OrderId = 5,
                            QuestionId = 5,
                            Text = "Rocket League"
                        },
                        new
                        {
                            Id = new Guid("a3f680f1-9b95-419c-96ec-72160b629ad8"),
                            NextQuestionId = 8,
                            OrderId = 6,
                            QuestionId = 5,
                            Text = "Apex Legends"
                        },
                        new
                        {
                            Id = new Guid("7d918892-9afd-4cba-86d3-2962a18df3e6"),
                            NextQuestionId = 8,
                            OrderId = 7,
                            QuestionId = 5,
                            Text = "Phasmophobia"
                        },
                        new
                        {
                            Id = new Guid("01bbfbda-ccdc-4dd7-bd26-3389f7fbbbd3"),
                            NextQuestionId = 8,
                            OrderId = 8,
                            QuestionId = 5,
                            Text = "Dead by Daylight"
                        },
                        new
                        {
                            Id = new Guid("f7dcb988-ae6c-4a77-adb4-d1eb85192485"),
                            NextQuestionId = 8,
                            OrderId = 9,
                            QuestionId = 5,
                            Text = "Tom Clancy's Rainbow Six: Siege"
                        },
                        new
                        {
                            Id = new Guid("56c14cea-3e61-4ca3-a127-e3941042b00c"),
                            NextQuestionId = 8,
                            OrderId = 10,
                            QuestionId = 5,
                            Text = "Team Fortress 2"
                        },
                        new
                        {
                            Id = new Guid("30b14c4b-facf-4f3a-82ea-9bec868bdde9"),
                            NextQuestionId = 8,
                            OrderId = 11,
                            QuestionId = 5,
                            Text = "Rust"
                        },
                        new
                        {
                            Id = new Guid("61c52c73-00fc-4c0e-b6e6-5302726c3fc8"),
                            NextQuestionId = 8,
                            OrderId = 12,
                            QuestionId = 5,
                            Text = "Destiny 2"
                        },
                        new
                        {
                            Id = new Guid("6d2aab9a-03a6-4194-9617-1d5f44c76ad4"),
                            NextQuestionId = 8,
                            OrderId = 13,
                            QuestionId = 5,
                            Text = "PLAYERUNKNOWN'S BATTLEGROUNDS"
                        },
                        new
                        {
                            Id = new Guid("841c08d4-45bb-44b6-94f5-7a9d26e79b34"),
                            NextQuestionId = 8,
                            OrderId = 14,
                            QuestionId = 5,
                            Text = "Garry's Mod"
                        },
                        new
                        {
                            Id = new Guid("f5ac6db7-9598-41ae-801a-de5089b23d5f"),
                            NextQuestionId = 8,
                            OrderId = 15,
                            QuestionId = 5,
                            Text = "Left 4 Dead 2"
                        },
                        new
                        {
                            Id = new Guid("984fe764-3a95-45e7-872f-38e21b3b2c7b"),
                            NextQuestionId = 8,
                            OrderId = 16,
                            QuestionId = 5,
                            Text = "Bloons TD 6"
                        },
                        new
                        {
                            Id = new Guid("c7dbcbfc-3822-487f-b4cb-8929701e87f3"),
                            NextQuestionId = 8,
                            OrderId = 17,
                            QuestionId = 5,
                            Text = "Brawlhalla"
                        },
                        new
                        {
                            Id = new Guid("f119bc84-a6a2-49ec-968d-908decddf95b"),
                            NextQuestionId = 8,
                            OrderId = 18,
                            QuestionId = 5,
                            Text = "Euro Truck Simulator 2"
                        },
                        new
                        {
                            Id = new Guid("34a6d8ac-0568-4916-a58c-fcd2da461ae8"),
                            NextQuestionId = 8,
                            OrderId = 19,
                            QuestionId = 5,
                            Text = "Among Us"
                        },
                        new
                        {
                            Id = new Guid("0730afed-3cae-42be-9f60-9345ddb7c672"),
                            NextQuestionId = 8,
                            OrderId = 20,
                            QuestionId = 5,
                            Text = "Grand Theft Auto 5"
                        },
                        new
                        {
                            Id = new Guid("ac388d86-9ca2-41df-8a9e-509f8673d19a"),
                            NextQuestionId = 7,
                            OrderId = 1,
                            QuestionId = 6,
                            Text = "Ja"
                        },
                        new
                        {
                            Id = new Guid("27f6775b-39e0-4d86-9c56-d850033055e9"),
                            NextQuestionId = 7,
                            OrderId = 2,
                            QuestionId = 6,
                            Text = "Nee"
                        },
                        new
                        {
                            Id = new Guid("b368fc25-4567-4c05-8af5-e6b5800bb483"),
                            NextQuestionId = 8,
                            OrderId = 1,
                            QuestionId = 7,
                            Text = "Ja"
                        },
                        new
                        {
                            Id = new Guid("dfdbca80-8e79-433b-bd63-5d941bd91c7d"),
                            NextQuestionId = 8,
                            OrderId = 2,
                            QuestionId = 7,
                            Text = "Nee"
                        },
                        new
                        {
                            Id = new Guid("6623f2a3-9817-47da-8ebd-47acaee82c05"),
                            NextQuestionId = 9,
                            OrderId = 1,
                            QuestionId = 8,
                            Text = "FPS"
                        },
                        new
                        {
                            Id = new Guid("58216027-fbf7-4d0e-bf07-65e81b329a64"),
                            NextQuestionId = 9,
                            OrderId = 2,
                            QuestionId = 8,
                            Text = "Graphics"
                        },
                        new
                        {
                            Id = new Guid("02626ba1-8013-45be-beae-c48f1bfcf370"),
                            NextQuestionId = 1,
                            OrderId = 1,
                            QuestionId = 9,
                            Text = "13'"
                        },
                        new
                        {
                            Id = new Guid("d8c91324-7247-4074-83dd-a42c94c9b50b"),
                            NextQuestionId = 1,
                            OrderId = 2,
                            QuestionId = 9,
                            Text = "14'"
                        },
                        new
                        {
                            Id = new Guid("bfb574c2-df13-4458-b1f7-6c90267a1aa1"),
                            NextQuestionId = 1,
                            OrderId = 3,
                            QuestionId = 9,
                            Text = "15'6"
                        },
                        new
                        {
                            Id = new Guid("e70500ae-b08b-48f4-9d2c-01046b600bdc"),
                            NextQuestionId = 1,
                            OrderId = 4,
                            QuestionId = 9,
                            Text = "17'"
                        });
                });

            modelBuilder.Entity("nl.Commen.Models.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cebd2418-71a5-4b63-b2d0-dc55fff4ebf3"),
                            Name = "3",
                            Score = 3,
                            Type = "Processor"
                        },
                        new
                        {
                            Id = new Guid("9a3eb040-6d84-47d0-9b57-81b017411658"),
                            Name = "5",
                            Score = 6,
                            Type = "Processor"
                        },
                        new
                        {
                            Id = new Guid("65a50f74-025e-4304-abfe-e327d3485e0e"),
                            Name = "7",
                            Score = 9,
                            Type = "Processor"
                        },
                        new
                        {
                            Id = new Guid("06fe91ab-7ed2-4252-9399-236ecd712729"),
                            Name = "256gb",
                            Score = 3,
                            Type = "Storage"
                        },
                        new
                        {
                            Id = new Guid("dd858fd4-f5d0-4b9e-83c3-45b8167d8640"),
                            Name = "512gb",
                            Score = 6,
                            Type = "Storage"
                        },
                        new
                        {
                            Id = new Guid("67700c6d-e573-4a41-8ae4-e258eb20e344"),
                            Name = "1tb",
                            Score = 9,
                            Type = "Storage"
                        },
                        new
                        {
                            Id = new Guid("b7f38dc7-f9dd-4592-b1a9-b9c2826ea6f7"),
                            Name = "8gb",
                            Score = 3,
                            Type = "Ram"
                        },
                        new
                        {
                            Id = new Guid("ef314576-5652-4384-96e1-896b8dee4d8d"),
                            Name = "16gb",
                            Score = 6,
                            Type = "Ram"
                        },
                        new
                        {
                            Id = new Guid("2c310a5b-d16c-4091-80c7-be5b4b783270"),
                            Name = "32gb",
                            Score = 9,
                            Type = "Ram"
                        },
                        new
                        {
                            Id = new Guid("72103b06-a256-439b-a8c3-360f07e5fe91"),
                            Name = "geen",
                            Score = 1,
                            Type = "GraphicsCard"
                        },
                        new
                        {
                            Id = new Guid("fc640f8d-d977-44b5-826c-3568eb01aa3c"),
                            Name = "1650-1660",
                            Score = 3,
                            Type = "GraphicsCard"
                        },
                        new
                        {
                            Id = new Guid("c7c4fe18-f6f3-41ff-9607-e0141ba7b2c7"),
                            Name = "2060/3050-2070/3060",
                            Score = 5,
                            Type = "GraphicsCard"
                        },
                        new
                        {
                            Id = new Guid("10a1d763-12a1-4a7c-abe9-fdd106232cb5"),
                            Name = "2070/3070-2080ti/3090",
                            Score = 8,
                            Type = "GraphicsCard"
                        },
                        new
                        {
                            Id = new Guid("b374df2e-ee2c-44fd-9feb-42fffabc714c"),
                            Name = "13'",
                            Score = 1,
                            Type = "ScreenSize"
                        },
                        new
                        {
                            Id = new Guid("be0787e5-9e09-453c-b81e-c9005f1c7f7b"),
                            Name = "14'",
                            Score = 2,
                            Type = "ScreenSize"
                        },
                        new
                        {
                            Id = new Guid("12e2e5b1-3419-4d8e-af19-2c48584f26ce"),
                            Name = "15'6",
                            Score = 3,
                            Type = "ScreenSize"
                        },
                        new
                        {
                            Id = new Guid("8fcb8177-1dca-42dc-9144-5ed2209b209b"),
                            Name = "17'",
                            Score = 4,
                            Type = "ScreenSize"
                        });
                });

            modelBuilder.Entity("nl.Commen.Models.Laptop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("GraphicsCard")
                        .HasColumnType("longtext");

                    b.Property<string>("Price")
                        .HasColumnType("longtext");

                    b.Property<string>("Processor")
                        .HasColumnType("longtext");

                    b.Property<string>("Ram")
                        .HasColumnType("longtext");

                    b.Property<string>("ScreenSize")
                        .HasColumnType("longtext");

                    b.Property<string>("Storage")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Laptops");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7812f40e-f253-487b-a639-3dfb0a2301b6"),
                            Price = "300"
                        },
                        new
                        {
                            Id = new Guid("cbc2355b-bd36-43d1-9631-ec051e11dc6d"),
                            Price = "500"
                        },
                        new
                        {
                            Id = new Guid("9cc2ab92-e382-4b7b-a154-e361452e5de8"),
                            Price = "800"
                        },
                        new
                        {
                            Id = new Guid("644f5b17-b080-4702-84f0-1811d975b1b9"),
                            Price = "1200"
                        },
                        new
                        {
                            Id = new Guid("a4391628-70eb-4852-a168-8572e281c332"),
                            Price = "300"
                        },
                        new
                        {
                            Id = new Guid("404ee053-9b72-414f-b78d-1cd9dd2cc6ce"),
                            Price = "500"
                        },
                        new
                        {
                            Id = new Guid("763fa443-2d90-4d77-a4cd-fd6e4d9cf989"),
                            Price = "800"
                        },
                        new
                        {
                            Id = new Guid("ea0c894b-7825-4fbf-9097-0aeb2a04c5d0"),
                            Price = "1200"
                        },
                        new
                        {
                            Id = new Guid("555a824d-ad98-4306-95a0-ab5d75848cd1"),
                            Price = "300"
                        },
                        new
                        {
                            Id = new Guid("a68d9f64-7f00-44b5-8dfc-fa0a5fb41406"),
                            Price = "500"
                        },
                        new
                        {
                            Id = new Guid("63ba6fd1-26c5-4792-a608-d000d90f9d31"),
                            Price = "800"
                        },
                        new
                        {
                            Id = new Guid("7bb7e848-e6b5-4027-8a88-8dcde4781ee5"),
                            Price = "1200"
                        },
                        new
                        {
                            Id = new Guid("c36004d2-483a-433e-a921-31a47ee02fbb"),
                            Price = "300"
                        },
                        new
                        {
                            Id = new Guid("06b6f337-ccb2-43a6-aa4c-a5be1c92f38e"),
                            Price = "500"
                        },
                        new
                        {
                            Id = new Guid("f289efed-564b-498b-a968-143f04ac23bb"),
                            Price = "800"
                        },
                        new
                        {
                            Id = new Guid("add60134-0031-46f9-99aa-800ba7dbe89e"),
                            Price = "1200"
                        });
                });

            modelBuilder.Entity("nl.Commen.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Question");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = "Hoeveel geld wilt u besteden?"
                        },
                        new
                        {
                            Id = 2,
                            Text = "Waar ga je je laptop voor gebruiken?"
                        },
                        new
                        {
                            Id = 3,
                            Text = "Is het vooral video of foto bewerking?"
                        },
                        new
                        {
                            Id = 4,
                            Text = "Wat voor soort games speelt u?"
                        },
                        new
                        {
                            Id = 5,
                            Text = "Welke van de onderstaande games heeft u gespeeld of bent u van plan te spelen?"
                        },
                        new
                        {
                            Id = 6,
                            Text = "Doet u het professioneel?"
                        },
                        new
                        {
                            Id = 7,
                            Text = "Heeft u vaak veel programma's tegelijkertijd aanstaan? (4 of meer)"
                        },
                        new
                        {
                            Id = 8,
                            Text = "Heeft U liever meer FPS, en/of betere graphics"
                        },
                        new
                        {
                            Id = 9,
                            Text = "Welk grootte scherm heeft u het liefst"
                        });
                });

            modelBuilder.Entity("nl.Commen.Models.SingleAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AnswerId")
                        .HasColumnType("longtext");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UserAnswerId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserAnswerId");

                    b.ToTable("SingeAnswers");
                });

            modelBuilder.Entity("nl.Commen.Models.SingleAnswerTemp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AnswerId")
                        .HasColumnType("longtext");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SingleAnswerTemp");
                });

            modelBuilder.Entity("nl.Commen.Models.UserAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UserAnswers");
                });

            modelBuilder.Entity("nl.Commen.Models.SingleAnswer", b =>
                {
                    b.HasOne("nl.Commen.Models.UserAnswer", null)
                        .WithMany("Answers")
                        .HasForeignKey("UserAnswerId");
                });

            modelBuilder.Entity("nl.Commen.Models.UserAnswer", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
