// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nl.Data;

namespace nl.Data.Migrations
{
    [DbContext(typeof(NlTutContext))]
    [Migration("20220112213920_AnswerOrderId")]
    partial class AnswerOrderId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("nl.Commen.Models.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("NextQuestionId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Answer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6cd58ac4-9d70-411e-a228-65d7bc1a0b33"),
                            NextQuestionId = 2,
                            OrderId = 1,
                            QuestionId = 1,
                            Text = "300-500"
                        },
                        new
                        {
                            Id = new Guid("159c6de5-1800-4c52-b879-3c523eca7d22"),
                            NextQuestionId = 2,
                            OrderId = 2,
                            QuestionId = 1,
                            Text = "500-800"
                        },
                        new
                        {
                            Id = new Guid("ea0192c9-f657-4cf9-86e8-bbca2dba4793"),
                            NextQuestionId = 2,
                            OrderId = 3,
                            QuestionId = 1,
                            Text = "800-1200"
                        },
                        new
                        {
                            Id = new Guid("604a5bfc-b19c-4eae-bba5-0aedbf0652af"),
                            NextQuestionId = 2,
                            OrderId = 4,
                            QuestionId = 1,
                            Text = "1200+"
                        },
                        new
                        {
                            Id = new Guid("efe31ec8-f8b4-4ce0-857f-971350258864"),
                            NextQuestionId = 7,
                            OrderId = 1,
                            QuestionId = 2,
                            Text = "Mail / Netflix & YouTube"
                        },
                        new
                        {
                            Id = new Guid("1519b0ab-3b1e-47e7-9a53-cb9dd01a713b"),
                            NextQuestionId = 7,
                            OrderId = 2,
                            QuestionId = 2,
                            Text = "Documenten bewerken"
                        },
                        new
                        {
                            Id = new Guid("5f1fbe5b-0e57-47b8-8a63-af1cdf2880e8"),
                            NextQuestionId = 3,
                            OrderId = 3,
                            QuestionId = 2,
                            Text = "Foto's/video's bewerken"
                        },
                        new
                        {
                            Id = new Guid("73717be5-812a-4f84-9106-9c19dac9e8f9"),
                            NextQuestionId = 4,
                            OrderId = 4,
                            QuestionId = 2,
                            Text = "Gamen"
                        },
                        new
                        {
                            Id = new Guid("7f17a881-4e4e-42ae-866f-8b6750e43aa7"),
                            NextQuestionId = 6,
                            OrderId = 1,
                            QuestionId = 3,
                            Text = "Foto's"
                        },
                        new
                        {
                            Id = new Guid("7036756b-6a83-46db-8882-62ce95506c8f"),
                            NextQuestionId = 6,
                            OrderId = 2,
                            QuestionId = 3,
                            Text = "Video's"
                        },
                        new
                        {
                            Id = new Guid("5d80a4aa-b658-40a5-9246-d7d1b28a7fc3"),
                            NextQuestionId = 5,
                            OrderId = 1,
                            QuestionId = 4,
                            Text = "Shooters"
                        },
                        new
                        {
                            Id = new Guid("73bc109a-f762-46d7-b1a4-6219614dedf2"),
                            NextQuestionId = 5,
                            OrderId = 2,
                            QuestionId = 4,
                            Text = "Moba"
                        },
                        new
                        {
                            Id = new Guid("54c140d2-56c2-4171-b223-adf81fd222b4"),
                            NextQuestionId = 5,
                            OrderId = 3,
                            QuestionId = 4,
                            Text = "Action-adventure"
                        },
                        new
                        {
                            Id = new Guid("3a2b3e37-6b21-4d98-88b8-e60d196c803f"),
                            NextQuestionId = 5,
                            OrderId = 4,
                            QuestionId = 4,
                            Text = "Esports"
                        },
                        new
                        {
                            Id = new Guid("d78cc0a0-a08e-4fa1-82e0-d62185ce2617"),
                            NextQuestionId = 5,
                            OrderId = 5,
                            QuestionId = 4,
                            Text = "Real-time strategy"
                        },
                        new
                        {
                            Id = new Guid("fbe341d3-0b7a-4413-b601-77e70fc2d679"),
                            NextQuestionId = 8,
                            OrderId = 1,
                            QuestionId = 5,
                            Text = "Counter-Strike: Global Offensive"
                        },
                        new
                        {
                            Id = new Guid("f6c420e9-d6b0-49e8-af67-78df00f908b1"),
                            NextQuestionId = 8,
                            OrderId = 2,
                            QuestionId = 5,
                            Text = "New World"
                        },
                        new
                        {
                            Id = new Guid("37dc0e96-ec9f-4d9d-8758-1005e8f00144"),
                            NextQuestionId = 8,
                            OrderId = 3,
                            QuestionId = 5,
                            Text = "Dota 2"
                        },
                        new
                        {
                            Id = new Guid("5bee999e-65a9-4460-9ecb-e9a8e0cb2f95"),
                            NextQuestionId = 8,
                            OrderId = 4,
                            QuestionId = 5,
                            Text = "Battlefield 2042"
                        },
                        new
                        {
                            Id = new Guid("66196289-8542-4a5a-911c-1bbc5d668147"),
                            NextQuestionId = 8,
                            OrderId = 5,
                            QuestionId = 5,
                            Text = "Rocket League"
                        },
                        new
                        {
                            Id = new Guid("1ca52788-9b7f-45a2-82ea-d11865620ffd"),
                            NextQuestionId = 8,
                            OrderId = 6,
                            QuestionId = 5,
                            Text = "Apex Legends"
                        },
                        new
                        {
                            Id = new Guid("8e51a8f0-8203-47d9-b531-bfa95b23c74a"),
                            NextQuestionId = 8,
                            OrderId = 7,
                            QuestionId = 5,
                            Text = "Phasmophobia"
                        },
                        new
                        {
                            Id = new Guid("4d2e20be-9f41-4103-be2c-2562be1d70e4"),
                            NextQuestionId = 8,
                            OrderId = 8,
                            QuestionId = 5,
                            Text = "Dead by Daylight"
                        },
                        new
                        {
                            Id = new Guid("c700ddef-b9ee-4c93-b838-e50cd9b5a1ba"),
                            NextQuestionId = 8,
                            OrderId = 9,
                            QuestionId = 5,
                            Text = "Tom Clancy's Rainbow Six: Siege"
                        },
                        new
                        {
                            Id = new Guid("f20a8b11-648d-40b0-bb7f-90f2386658fb"),
                            NextQuestionId = 8,
                            OrderId = 10,
                            QuestionId = 5,
                            Text = "Team Fortress 2"
                        },
                        new
                        {
                            Id = new Guid("da548114-4349-4d4a-9d8d-1141e91efdb8"),
                            NextQuestionId = 8,
                            OrderId = 11,
                            QuestionId = 5,
                            Text = "Rust"
                        },
                        new
                        {
                            Id = new Guid("a0a43c26-7507-4b42-9e8d-bec433b5e7d3"),
                            NextQuestionId = 8,
                            OrderId = 12,
                            QuestionId = 5,
                            Text = "Destiny 2"
                        },
                        new
                        {
                            Id = new Guid("2fef33a8-cd18-42c8-9e92-3a8da7edf99f"),
                            NextQuestionId = 8,
                            OrderId = 13,
                            QuestionId = 5,
                            Text = "PLAYERUNKNOWN'S BATTLEGROUNDS"
                        },
                        new
                        {
                            Id = new Guid("be74846f-197e-4719-b27d-3c0e5a137e4e"),
                            NextQuestionId = 8,
                            OrderId = 14,
                            QuestionId = 5,
                            Text = "Garry's Mod"
                        },
                        new
                        {
                            Id = new Guid("88a8469c-2757-412b-9c25-05f9e0342c19"),
                            NextQuestionId = 8,
                            OrderId = 15,
                            QuestionId = 5,
                            Text = "Left 4 Dead 2"
                        },
                        new
                        {
                            Id = new Guid("6477c201-537d-427a-84c3-c7ec0e0d39b1"),
                            NextQuestionId = 8,
                            OrderId = 16,
                            QuestionId = 5,
                            Text = "Bloons TD 6"
                        },
                        new
                        {
                            Id = new Guid("e81fa931-0581-4b7e-a18c-5884ae8db945"),
                            NextQuestionId = 8,
                            OrderId = 17,
                            QuestionId = 5,
                            Text = "Brawlhalla"
                        },
                        new
                        {
                            Id = new Guid("683b5e24-7409-461b-9636-30b290a646f1"),
                            NextQuestionId = 8,
                            OrderId = 18,
                            QuestionId = 5,
                            Text = "Euro Truck Simulator 2"
                        },
                        new
                        {
                            Id = new Guid("f8f95a8f-019c-47bf-accb-5a1e9eda4d37"),
                            NextQuestionId = 8,
                            OrderId = 19,
                            QuestionId = 5,
                            Text = "Among Us"
                        },
                        new
                        {
                            Id = new Guid("6e6c2f13-cf44-4cb7-b9da-b9a65ad07b0a"),
                            NextQuestionId = 8,
                            OrderId = 20,
                            QuestionId = 5,
                            Text = "Grand Theft Auto 5"
                        },
                        new
                        {
                            Id = new Guid("1b3913a2-c40d-4b30-9aed-cda73586c1a3"),
                            NextQuestionId = 7,
                            OrderId = 1,
                            QuestionId = 6,
                            Text = "Ja"
                        },
                        new
                        {
                            Id = new Guid("ef2309d4-7b3b-44a0-84e4-2118d1ea5efd"),
                            NextQuestionId = 7,
                            OrderId = 2,
                            QuestionId = 6,
                            Text = "Nee"
                        },
                        new
                        {
                            Id = new Guid("23c982fe-f27b-4137-934f-05bfef6cd850"),
                            NextQuestionId = 8,
                            OrderId = 1,
                            QuestionId = 7,
                            Text = "Ja"
                        },
                        new
                        {
                            Id = new Guid("48b15d0f-728e-46ba-9332-c15d5c8c6cc3"),
                            NextQuestionId = 8,
                            OrderId = 2,
                            QuestionId = 7,
                            Text = "Nee"
                        },
                        new
                        {
                            Id = new Guid("3bb83b6f-b798-4aa6-8a0f-8197bf483fe6"),
                            NextQuestionId = 9,
                            OrderId = 1,
                            QuestionId = 8,
                            Text = "FPS"
                        },
                        new
                        {
                            Id = new Guid("f10d3fa2-ba57-4048-9472-40a42d601432"),
                            NextQuestionId = 9,
                            OrderId = 2,
                            QuestionId = 8,
                            Text = "Graphics"
                        },
                        new
                        {
                            Id = new Guid("6096d70c-50ab-428e-a9d8-ef7457f8c0b3"),
                            NextQuestionId = 1,
                            OrderId = 1,
                            QuestionId = 9,
                            Text = "13'"
                        },
                        new
                        {
                            Id = new Guid("71e522a4-edb2-4241-8592-727865fd06d0"),
                            NextQuestionId = 1,
                            OrderId = 2,
                            QuestionId = 9,
                            Text = "14'"
                        },
                        new
                        {
                            Id = new Guid("51ba19ab-72fa-4c32-acc0-1099844ffcda"),
                            NextQuestionId = 1,
                            OrderId = 3,
                            QuestionId = 9,
                            Text = "15'6"
                        },
                        new
                        {
                            Id = new Guid("6ac68e1d-80f3-4203-9951-f57b8b1b239b"),
                            NextQuestionId = 1,
                            OrderId = 4,
                            QuestionId = 9,
                            Text = "17'"
                        });
                });

            modelBuilder.Entity("nl.Commen.Models.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Id = new Guid("16cea6de-7a32-44dc-a9e4-561934123c86"),
                            Name = "3",
                            Score = 3,
                            Type = "Processor"
                        },
                        new
                        {
                            Id = new Guid("f6d41a9e-b529-4d30-8ad4-3587cca18bb3"),
                            Name = "5",
                            Score = 6,
                            Type = "Processor"
                        },
                        new
                        {
                            Id = new Guid("e12e98be-288d-47f3-8de4-037f55334046"),
                            Name = "7",
                            Score = 9,
                            Type = "Processor"
                        },
                        new
                        {
                            Id = new Guid("fd8b17b7-e104-4c64-a1b3-476c573f3452"),
                            Name = "256gb",
                            Score = 3,
                            Type = "Storage"
                        },
                        new
                        {
                            Id = new Guid("3583370d-9231-47c9-8135-36aae0493812"),
                            Name = "512gb",
                            Score = 6,
                            Type = "Storage"
                        },
                        new
                        {
                            Id = new Guid("a23e5581-f92e-4339-a4c2-25d7df4583dd"),
                            Name = "1tb",
                            Score = 9,
                            Type = "Storage"
                        },
                        new
                        {
                            Id = new Guid("092d87bb-51f2-4e0e-a79c-1834c6ee8af0"),
                            Name = "8gb",
                            Score = 3,
                            Type = "Ram"
                        },
                        new
                        {
                            Id = new Guid("afc027be-076c-473e-8e0c-6267c1127394"),
                            Name = "16gb",
                            Score = 6,
                            Type = "Ram"
                        },
                        new
                        {
                            Id = new Guid("7d3411a2-b54b-4318-93f4-17da4b2255b3"),
                            Name = "32gb",
                            Score = 9,
                            Type = "Ram"
                        },
                        new
                        {
                            Id = new Guid("5e86c72d-1894-4ade-9421-d6686c414868"),
                            Name = "geen",
                            Score = 1,
                            Type = "GraphicsCard"
                        },
                        new
                        {
                            Id = new Guid("396e0764-9db0-4d0c-90b6-34efe279dd42"),
                            Name = "1650-1660",
                            Score = 3,
                            Type = "GraphicsCard"
                        },
                        new
                        {
                            Id = new Guid("b41d9a98-9bc7-47a0-a641-b756c6db17e1"),
                            Name = "2060/3050-2070/3060",
                            Score = 5,
                            Type = "GraphicsCard"
                        },
                        new
                        {
                            Id = new Guid("9ccda705-3b1c-4674-9f71-e28a0438c7cc"),
                            Name = "2070/3070-2080ti/3090",
                            Score = 8,
                            Type = "GraphicsCard"
                        },
                        new
                        {
                            Id = new Guid("a70786d3-9119-4e95-87a0-20db4fea0cb6"),
                            Name = "13'",
                            Score = 1,
                            Type = "Processor"
                        },
                        new
                        {
                            Id = new Guid("a9198d26-fde1-4d5b-ac75-7c3cc1de831e"),
                            Name = "14'",
                            Score = 2,
                            Type = "Processor"
                        },
                        new
                        {
                            Id = new Guid("ff9b4679-3cdf-47b1-bab0-a239eeda9741"),
                            Name = "15'6",
                            Score = 3,
                            Type = "Processor"
                        },
                        new
                        {
                            Id = new Guid("0010cf50-e554-4261-8fa5-c1f265bad14f"),
                            Name = "17'",
                            Score = 4,
                            Type = "Processor"
                        });
                });

            modelBuilder.Entity("nl.Commen.Models.Laptop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("GraphicsCard")
                        .HasColumnType("longtext");

                    b.Property<string>("Price")
                        .HasColumnType("longtext");

                    b.Property<string>("Processor")
                        .HasColumnType("longtext");

                    b.Property<string>("Ram")
                        .HasColumnType("longtext");

                    b.Property<string>("ScreenSize")
                        .HasColumnType("longtext");

                    b.Property<string>("Storage")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Laptops");

                    b.HasData(
                        new
                        {
                            Id = new Guid("366afa02-df45-46d3-a86f-b95a71318ae8"),
                            Price = "300"
                        },
                        new
                        {
                            Id = new Guid("a825383c-c0e1-4bee-a072-1263e414a8d4"),
                            Price = "500"
                        },
                        new
                        {
                            Id = new Guid("2e52b1e4-fd27-4df8-87d8-93930ca1d871"),
                            Price = "800"
                        },
                        new
                        {
                            Id = new Guid("25cf75dc-0a0f-4b7a-baf4-9bb1b73149bf"),
                            Price = "1200"
                        },
                        new
                        {
                            Id = new Guid("0f9f3ddf-674a-4f02-8946-de189f211d48"),
                            Price = "300"
                        },
                        new
                        {
                            Id = new Guid("9b04ed3e-172c-46df-adba-4a0e8a1f8df3"),
                            Price = "500"
                        },
                        new
                        {
                            Id = new Guid("b4d96b70-6d44-4f5b-be8b-9b7a15417fc5"),
                            Price = "800"
                        },
                        new
                        {
                            Id = new Guid("c9f3665b-ddc0-4a96-890a-c9cdcb627f79"),
                            Price = "1200"
                        },
                        new
                        {
                            Id = new Guid("19aed9ff-93bb-4d07-87ca-466f99e8f4a3"),
                            Price = "300"
                        },
                        new
                        {
                            Id = new Guid("5d08e130-7854-440c-9656-434ac84ac01a"),
                            Price = "500"
                        },
                        new
                        {
                            Id = new Guid("da2315e2-a2f9-4bb5-8a7c-2d7f5cae932e"),
                            Price = "800"
                        },
                        new
                        {
                            Id = new Guid("54ac84be-9c36-421c-8a85-536fb1c6ed09"),
                            Price = "1200"
                        },
                        new
                        {
                            Id = new Guid("cbda845e-20a3-47cf-aa00-76c9b221ac9f"),
                            Price = "300"
                        },
                        new
                        {
                            Id = new Guid("ab135fb4-b66b-407b-97fe-2f9c814d3ea3"),
                            Price = "500"
                        },
                        new
                        {
                            Id = new Guid("09d0b616-ea09-45e0-bc75-e855596acda6"),
                            Price = "800"
                        },
                        new
                        {
                            Id = new Guid("187648ae-faee-4924-b608-a15e14f29027"),
                            Price = "1200"
                        });
                });

            modelBuilder.Entity("nl.Commen.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Question");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = "Hoeveel geld wilt u besteden?"
                        },
                        new
                        {
                            Id = 2,
                            Text = "Waar ga je je laptop voor gebruiken?"
                        },
                        new
                        {
                            Id = 3,
                            Text = "Is het vooral video of foto bewerking?"
                        },
                        new
                        {
                            Id = 4,
                            Text = "Wat voor soort games speelt u?"
                        },
                        new
                        {
                            Id = 5,
                            Text = "Welke van de onderstaande games heeft u gespeeld of bent u van plan te spelen?"
                        },
                        new
                        {
                            Id = 6,
                            Text = "Doet u het professioneel?"
                        },
                        new
                        {
                            Id = 7,
                            Text = "Heeft u vaak veel programma's tegelijkertijd aanstaan? (4 of meer)"
                        },
                        new
                        {
                            Id = 8,
                            Text = "Heeft U liever meer FPS, en/of betere graphics"
                        },
                        new
                        {
                            Id = 9,
                            Text = "Welk grootte scherm heeft u het liefst"
                        });
                });

            modelBuilder.Entity("nl.Commen.Models.SingleAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AnswerId")
                        .HasColumnType("longtext");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UserAnswerId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserAnswerId");

                    b.ToTable("SingeAnswers");
                });

            modelBuilder.Entity("nl.Commen.Models.SingleAnswerTemp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AnswerId")
                        .HasColumnType("longtext");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SingleAnswerTemp");
                });

            modelBuilder.Entity("nl.Commen.Models.UserAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UserAnswers");
                });

            modelBuilder.Entity("nl.Commen.Models.SingleAnswer", b =>
                {
                    b.HasOne("nl.Commen.Models.UserAnswer", null)
                        .WithMany("Answers")
                        .HasForeignKey("UserAnswerId");
                });

            modelBuilder.Entity("nl.Commen.Models.UserAnswer", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
