// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nl.Data;

namespace nl.Data.Migrations
{
    [DbContext(typeof(NlTutContext))]
    [Migration("20220112212846_Components")]
    partial class Components
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("nl.Commen.Models.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("NextQuestionId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Answer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("657e4aab-fc0d-4ee2-9e5f-8787fadf7e61"),
                            NextQuestionId = 2,
                            QuestionId = 1,
                            Text = "300-500"
                        },
                        new
                        {
                            Id = new Guid("c9ae4b66-1489-4bb2-ac97-ba74fbe93787"),
                            NextQuestionId = 2,
                            QuestionId = 1,
                            Text = "500-800"
                        },
                        new
                        {
                            Id = new Guid("3daa1f70-e50e-4654-9105-8d85583def20"),
                            NextQuestionId = 2,
                            QuestionId = 1,
                            Text = "800-1200"
                        },
                        new
                        {
                            Id = new Guid("277ca894-5e43-4486-8ff1-4778620bf568"),
                            NextQuestionId = 2,
                            QuestionId = 1,
                            Text = "1200+"
                        },
                        new
                        {
                            Id = new Guid("772f604b-e22d-4ee3-8d7b-9ebb24aa783c"),
                            NextQuestionId = 7,
                            QuestionId = 2,
                            Text = "Mail / Netflix & YouTube"
                        },
                        new
                        {
                            Id = new Guid("63ae4641-01e7-4d6b-8f46-9aa0417cf8e4"),
                            NextQuestionId = 7,
                            QuestionId = 2,
                            Text = "Documenten bewerken"
                        },
                        new
                        {
                            Id = new Guid("66283355-80d6-4abb-90c6-b321068cbbfa"),
                            NextQuestionId = 3,
                            QuestionId = 2,
                            Text = "Foto's/video's bewerken"
                        },
                        new
                        {
                            Id = new Guid("44b36696-24f5-4422-a0a4-51dfc21120c8"),
                            NextQuestionId = 4,
                            QuestionId = 2,
                            Text = "Gamen"
                        },
                        new
                        {
                            Id = new Guid("87c4ae8d-a953-4575-ac84-a6085a2fa728"),
                            NextQuestionId = 6,
                            QuestionId = 3,
                            Text = "Foto's"
                        },
                        new
                        {
                            Id = new Guid("cb18a83d-b5cb-4f4d-9249-1781da9d17de"),
                            NextQuestionId = 6,
                            QuestionId = 3,
                            Text = "Video's"
                        },
                        new
                        {
                            Id = new Guid("5ae28bfe-72e5-467f-88f8-ead91f018836"),
                            NextQuestionId = 5,
                            QuestionId = 4,
                            Text = "Shooters"
                        },
                        new
                        {
                            Id = new Guid("71de863e-2ede-48e0-b51b-f211dd5589bf"),
                            NextQuestionId = 5,
                            QuestionId = 4,
                            Text = "Moba"
                        },
                        new
                        {
                            Id = new Guid("0816a06d-4ea3-4d1a-9e8b-b7f8f0a63887"),
                            NextQuestionId = 5,
                            QuestionId = 4,
                            Text = "Action-adventure"
                        },
                        new
                        {
                            Id = new Guid("6df82aac-8534-47cb-b694-109ab8e762c4"),
                            NextQuestionId = 5,
                            QuestionId = 4,
                            Text = "Esports"
                        },
                        new
                        {
                            Id = new Guid("685e3e39-aed8-47d9-a07d-3121bf219809"),
                            NextQuestionId = 5,
                            QuestionId = 4,
                            Text = "Real-time strategy"
                        },
                        new
                        {
                            Id = new Guid("b3ba7dec-25fd-4792-bca2-49d1ce1c0318"),
                            NextQuestionId = 8,
                            QuestionId = 5,
                            Text = "Counter-Strike: Global Offensive"
                        },
                        new
                        {
                            Id = new Guid("b57faf26-8373-45df-888d-2992e1412865"),
                            NextQuestionId = 8,
                            QuestionId = 5,
                            Text = "New World"
                        },
                        new
                        {
                            Id = new Guid("8765a45a-f11f-48fb-9a36-8a8e8fd88a79"),
                            NextQuestionId = 8,
                            QuestionId = 5,
                            Text = "Dota 2"
                        },
                        new
                        {
                            Id = new Guid("8e972769-79fc-4c13-bb6b-96d7ba873c00"),
                            NextQuestionId = 8,
                            QuestionId = 5,
                            Text = "Battlefield 2042"
                        },
                        new
                        {
                            Id = new Guid("fa82fa85-191e-4fae-98e7-f8df7c4720a9"),
                            NextQuestionId = 8,
                            QuestionId = 5,
                            Text = "Rocket League"
                        },
                        new
                        {
                            Id = new Guid("b42955a3-d0f8-4881-85b5-ce8c98098f81"),
                            NextQuestionId = 8,
                            QuestionId = 5,
                            Text = "Apex Legends"
                        },
                        new
                        {
                            Id = new Guid("da920d9b-25a8-4ae4-b226-0ebdd3e8fae1"),
                            NextQuestionId = 8,
                            QuestionId = 5,
                            Text = "Phasmophobia"
                        },
                        new
                        {
                            Id = new Guid("16832641-7376-47e7-9a74-412ab37eaf6b"),
                            NextQuestionId = 8,
                            QuestionId = 5,
                            Text = "Dead by Daylight"
                        },
                        new
                        {
                            Id = new Guid("9e3be877-cd0e-4ff6-a7d5-43a91eca75c1"),
                            NextQuestionId = 8,
                            QuestionId = 5,
                            Text = "Tom Clancy's Rainbow Six: Siege"
                        },
                        new
                        {
                            Id = new Guid("2c042474-4586-4cb4-8d00-21d943a32033"),
                            NextQuestionId = 8,
                            QuestionId = 5,
                            Text = "Team Fortress 2"
                        },
                        new
                        {
                            Id = new Guid("1051028c-3288-4b1e-8bcb-4a54bba2b963"),
                            NextQuestionId = 8,
                            QuestionId = 5,
                            Text = "Rust"
                        },
                        new
                        {
                            Id = new Guid("13879e23-bf73-4d57-8bc6-64ce6ffaca6c"),
                            NextQuestionId = 8,
                            QuestionId = 5,
                            Text = "Destiny 2"
                        },
                        new
                        {
                            Id = new Guid("be8fe0ea-4e29-4196-b1f3-0067221117b2"),
                            NextQuestionId = 8,
                            QuestionId = 5,
                            Text = "PLAYERUNKNOWN'S BATTLEGROUNDS"
                        },
                        new
                        {
                            Id = new Guid("5bfb6a6f-1df8-4fbb-af8c-47de0f32c0c2"),
                            NextQuestionId = 8,
                            QuestionId = 5,
                            Text = "Garry's Mod"
                        },
                        new
                        {
                            Id = new Guid("5b4916a7-efe1-45a4-a923-b06223c8e0c7"),
                            NextQuestionId = 8,
                            QuestionId = 5,
                            Text = "Left 4 Dead 2"
                        },
                        new
                        {
                            Id = new Guid("430a380b-6ed1-4b3e-a666-82fa94c0ab72"),
                            NextQuestionId = 8,
                            QuestionId = 5,
                            Text = "Bloons TD 6"
                        },
                        new
                        {
                            Id = new Guid("bb1a0fba-6570-4511-8b19-f8cb4bc7401e"),
                            NextQuestionId = 8,
                            QuestionId = 5,
                            Text = "Brawlhalla"
                        },
                        new
                        {
                            Id = new Guid("eb1eb29b-aed5-4d2d-8a8e-88a33285c4a0"),
                            NextQuestionId = 8,
                            QuestionId = 5,
                            Text = "Euro Truck Simulator 2"
                        },
                        new
                        {
                            Id = new Guid("6c3e98eb-63b7-47fb-8b5d-056430484ce9"),
                            NextQuestionId = 8,
                            QuestionId = 5,
                            Text = "Among Us"
                        },
                        new
                        {
                            Id = new Guid("57031833-6c18-4b31-b950-22031c71d8ab"),
                            NextQuestionId = 8,
                            QuestionId = 5,
                            Text = "Grand Theft Auto 5"
                        },
                        new
                        {
                            Id = new Guid("a5fd6b81-130b-4bfb-a10d-bfc698aaa80f"),
                            NextQuestionId = 7,
                            QuestionId = 6,
                            Text = "Ja"
                        },
                        new
                        {
                            Id = new Guid("c4100328-fd8f-48ba-9e1a-fc72c35c57df"),
                            NextQuestionId = 7,
                            QuestionId = 6,
                            Text = "Nee"
                        },
                        new
                        {
                            Id = new Guid("8afe2b68-fb8e-4016-beab-8e8104fe1dc3"),
                            NextQuestionId = 8,
                            QuestionId = 7,
                            Text = "Ja"
                        },
                        new
                        {
                            Id = new Guid("e2d06687-03fb-473a-a8e7-1602406d7dff"),
                            NextQuestionId = 8,
                            QuestionId = 7,
                            Text = "Nee"
                        },
                        new
                        {
                            Id = new Guid("0c5f0b8f-12b9-41e8-92b9-cd8702cea043"),
                            NextQuestionId = 9,
                            QuestionId = 8,
                            Text = "FPS"
                        },
                        new
                        {
                            Id = new Guid("b40eee6a-6d2b-4f16-a364-35f8abdb11ba"),
                            NextQuestionId = 9,
                            QuestionId = 8,
                            Text = "Graphics"
                        },
                        new
                        {
                            Id = new Guid("3efd1d44-9487-4846-8239-85e138d13e26"),
                            NextQuestionId = 1,
                            QuestionId = 9,
                            Text = "13'"
                        },
                        new
                        {
                            Id = new Guid("0bf09ef2-48dc-4bac-9b48-3690dff3f21f"),
                            NextQuestionId = 1,
                            QuestionId = 9,
                            Text = "14'"
                        },
                        new
                        {
                            Id = new Guid("c1463fad-1655-4a2b-a4a3-99550d4c19e4"),
                            NextQuestionId = 1,
                            QuestionId = 9,
                            Text = "15'6"
                        },
                        new
                        {
                            Id = new Guid("5a975786-3d16-4eb5-8ccf-c16b84216e5f"),
                            NextQuestionId = 1,
                            QuestionId = 9,
                            Text = "17'"
                        });
                });

            modelBuilder.Entity("nl.Commen.Models.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Id = new Guid("118a74e4-47c0-4a5a-804c-bc71d6054121"),
                            Name = "3",
                            Score = 3,
                            Type = "Processor"
                        },
                        new
                        {
                            Id = new Guid("b80d4c2e-f42b-42fa-861b-85cfa8626a40"),
                            Name = "5",
                            Score = 6,
                            Type = "Processor"
                        },
                        new
                        {
                            Id = new Guid("540ea434-d60b-4297-b064-2eba953e5290"),
                            Name = "7",
                            Score = 9,
                            Type = "Processor"
                        },
                        new
                        {
                            Id = new Guid("19c55fde-d7e8-4a70-a261-b9c735b60465"),
                            Name = "256gb",
                            Score = 3,
                            Type = "Storage"
                        },
                        new
                        {
                            Id = new Guid("0741dbba-4742-4e14-b1fc-87c7afeb37f6"),
                            Name = "512gb",
                            Score = 6,
                            Type = "Storage"
                        },
                        new
                        {
                            Id = new Guid("a8ed6635-6820-45a1-928c-dcf1d8669324"),
                            Name = "1tb",
                            Score = 9,
                            Type = "Storage"
                        },
                        new
                        {
                            Id = new Guid("c53fb704-53a8-41fc-8acc-f735fa8526d0"),
                            Name = "8gb",
                            Score = 3,
                            Type = "Ram"
                        },
                        new
                        {
                            Id = new Guid("279c027b-853c-41b9-b4f1-58f865803f1b"),
                            Name = "16gb",
                            Score = 6,
                            Type = "Ram"
                        },
                        new
                        {
                            Id = new Guid("07cd03dd-ac62-45d4-b3c3-e5e8e2e81207"),
                            Name = "32gb",
                            Score = 9,
                            Type = "Ram"
                        },
                        new
                        {
                            Id = new Guid("b94b3b0a-a67f-4272-b235-aae3c4b6c73e"),
                            Name = "geen",
                            Score = 1,
                            Type = "GraphicsCard"
                        },
                        new
                        {
                            Id = new Guid("621ba154-e419-4568-8cf5-173a009295cc"),
                            Name = "1650-1660",
                            Score = 3,
                            Type = "GraphicsCard"
                        },
                        new
                        {
                            Id = new Guid("4bf17de5-5ab9-4c88-930c-9517e1e23806"),
                            Name = "2060/3050-2070/3060",
                            Score = 5,
                            Type = "GraphicsCard"
                        },
                        new
                        {
                            Id = new Guid("bdcd864b-834d-41bd-8ad8-57fff917119a"),
                            Name = "2070/3070-2080ti/3090",
                            Score = 8,
                            Type = "GraphicsCard"
                        },
                        new
                        {
                            Id = new Guid("b517cc1f-10c8-4ff6-91cd-720b0a80d686"),
                            Name = "13'",
                            Score = 1,
                            Type = "Processor"
                        },
                        new
                        {
                            Id = new Guid("a73d9746-524b-4271-8de7-f2e9127fd3fd"),
                            Name = "14'",
                            Score = 2,
                            Type = "Processor"
                        },
                        new
                        {
                            Id = new Guid("4aa8777c-90c5-4da1-b092-155969eba13f"),
                            Name = "15'6",
                            Score = 3,
                            Type = "Processor"
                        },
                        new
                        {
                            Id = new Guid("39b79e23-56e7-4ba4-a313-ed5bdb021f46"),
                            Name = "17'",
                            Score = 4,
                            Type = "Processor"
                        });
                });

            modelBuilder.Entity("nl.Commen.Models.Laptop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("GraphicsCard")
                        .HasColumnType("longtext");

                    b.Property<string>("Price")
                        .HasColumnType("longtext");

                    b.Property<string>("Processor")
                        .HasColumnType("longtext");

                    b.Property<string>("Ram")
                        .HasColumnType("longtext");

                    b.Property<string>("ScreenSize")
                        .HasColumnType("longtext");

                    b.Property<string>("Storage")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Laptops");

                    b.HasData(
                        new
                        {
                            Id = new Guid("76af620c-e6c3-4726-ba9c-836758eb49c3"),
                            Price = "300"
                        },
                        new
                        {
                            Id = new Guid("e3aa5129-a8de-4f85-8cb2-32f0f7833566"),
                            Price = "500"
                        },
                        new
                        {
                            Id = new Guid("96ed5134-77de-4169-9a42-28c441c1c45b"),
                            Price = "800"
                        },
                        new
                        {
                            Id = new Guid("485dc9d6-8b72-43ab-9e55-66fc08752f52"),
                            Price = "1200"
                        },
                        new
                        {
                            Id = new Guid("98340ad1-40d2-489c-bd95-49145aa26179"),
                            Price = "300"
                        },
                        new
                        {
                            Id = new Guid("0a2d9944-b67f-4989-9f76-b19b8e1c4fb5"),
                            Price = "500"
                        },
                        new
                        {
                            Id = new Guid("13c04aaa-ad59-4794-98b7-1bd143554e43"),
                            Price = "800"
                        },
                        new
                        {
                            Id = new Guid("6e52b76c-87de-4ab4-a213-0b2d11fb2ccf"),
                            Price = "1200"
                        },
                        new
                        {
                            Id = new Guid("40fbc4fd-17c5-4ef7-bba2-cf028bab10f6"),
                            Price = "300"
                        },
                        new
                        {
                            Id = new Guid("c99f57a3-9269-48ba-8a8b-bc32a89de7b5"),
                            Price = "500"
                        },
                        new
                        {
                            Id = new Guid("6e883e65-3f8c-48a9-83b5-2edd3d6499c9"),
                            Price = "800"
                        },
                        new
                        {
                            Id = new Guid("041ccb50-d9f4-49a5-ba45-0a60744a6d1c"),
                            Price = "1200"
                        },
                        new
                        {
                            Id = new Guid("acced7d6-e3ff-4a09-a195-a78a09112d2f"),
                            Price = "300"
                        },
                        new
                        {
                            Id = new Guid("fbfb1870-e2dd-4711-8d20-57c98562d109"),
                            Price = "500"
                        },
                        new
                        {
                            Id = new Guid("0759b3fe-3b82-43ae-988f-bdd1563dbc32"),
                            Price = "800"
                        },
                        new
                        {
                            Id = new Guid("ad0c1524-2cc1-46fb-9399-03bcd55ec22a"),
                            Price = "1200"
                        });
                });

            modelBuilder.Entity("nl.Commen.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Question");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = "Hoeveel geld wilt u besteden?"
                        },
                        new
                        {
                            Id = 2,
                            Text = "Waar ga je je laptop voor gebruiken?"
                        },
                        new
                        {
                            Id = 3,
                            Text = "Is het vooral video of foto bewerking?"
                        },
                        new
                        {
                            Id = 4,
                            Text = "Wat voor soort games speelt u?"
                        },
                        new
                        {
                            Id = 5,
                            Text = "Welke van de onderstaande games heeft u gespeeld of bent u van plan te spelen?"
                        },
                        new
                        {
                            Id = 6,
                            Text = "Doet u het professioneel?"
                        },
                        new
                        {
                            Id = 7,
                            Text = "Heeft u vaak veel programma's tegelijkertijd aanstaan? (4 of meer)"
                        },
                        new
                        {
                            Id = 8,
                            Text = "Heeft U liever meer FPS, en/of betere graphics"
                        },
                        new
                        {
                            Id = 9,
                            Text = "Welk grootte scherm heeft u het liefst"
                        });
                });

            modelBuilder.Entity("nl.Commen.Models.SingleAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AnswerId")
                        .HasColumnType("longtext");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UserAnswerId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserAnswerId");

                    b.ToTable("SingeAnswers");
                });

            modelBuilder.Entity("nl.Commen.Models.SingleAnswerTemp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AnswerId")
                        .HasColumnType("longtext");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SingleAnswerTemp");
                });

            modelBuilder.Entity("nl.Commen.Models.UserAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UserAnswers");
                });

            modelBuilder.Entity("nl.Commen.Models.SingleAnswer", b =>
                {
                    b.HasOne("nl.Commen.Models.UserAnswer", null)
                        .WithMany("Answers")
                        .HasForeignKey("UserAnswerId");
                });

            modelBuilder.Entity("nl.Commen.Models.UserAnswer", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
